def check_question(question):
    medical_keywords = [
    'anxiety', 'depression', 'stress', 'panic', 'phobia', 'trauma', 'PTSD', 'obsessive-compulsive disorder',
    'eating disorder', 'bulimia', 'anorexia', 'body dysmorphic disorder', 'self-harm', 'suicide', 'suicidal thoughts',
    'bipolar disorder', 'mania', 'hypomania', 'schizophrenia', 'psychosis', 'borderline personality disorder',
    'dissociative identity disorder', 'substance abuse', 'addiction', 'alcoholism', 'drug abuse', 'recovery', 'relapse',
    'counseling', 'therapy', 'psychotherapy', 'cognitive behavioral therapy', 'CBT', 'dialectical behavior therapy', 'DBT',
    'mindfulness', 'meditation', 'relaxation', 'breathing exercises', 'grounding techniques', 'stress management',
    'self-care', 'self-compassion', 'positive affirmations', 'gratitude', 'journaling', 'therapy animals', 'emotional support animals',
    'social support', 'peer support', 'support groups', 'mental health awareness', 'stigma', 'advocacy', 'mental health education',
    'emotional wellbeing', 'resilience', 'self-esteem', 'self-confidence', 'identity', 'identity crisis', 'life satisfaction',
    'happiness', 'joy', 'fulfillment', 'meaning', 'purpose', 'boundaries', 'assertiveness', 'communication skills',
    'conflict resolution', 'anger management', 'forgiveness', 'grief', 'loss', 'bereavement', 'loneliness', 'isolation',
    'social anxiety', 'relationship issues', 'family dynamics', 'parenting stress', 'workplace stress', 'burnout', 'compassion fatigue',
    'sleep', 'insomnia', 'nightmares', 'restlessness', 'fatigue', 'physical health', 'exercise', 'nutrition', 'diet', 'hydration',
    'medical conditions', 'chronic illness', 'pain management', 'medication', 'side effects', 'treatment', 'recovery journey',
    'mental health resources', 'hotlines', 'crisis intervention', 'emergency services', 'helplines', 'online therapy',
    'mental health apps', 'mental health professionals', 'psychiatrist', 'psychologist', 'counselor', 'therapist', 'social worker',
    'peer counselor', 'rehabilitation services', 'inpatient treatment', 'outpatient treatment', 'community mental health services',
    'well-being', 'happiness', 'stress', 'anxiety', 'depression', 'mental health', 'emotional health', 'self-care',
    'mindfulness', 'meditation', 'therapy', 'counseling', 'support', 'wellness', 'balance', 'positive', 'negative',
    'relaxation', 'calm', 'peace', 'serenity', 'hope', 'resilience', 'recovery', 'strength', 'struggle', 'coping',
    'self-esteem', 'confidence', 'self-compassion', 'gratitude', 'joy', 'fulfillment', 'purpose', 'meaning', 'identity',
    'hobby', 'interest', 'passion', 'connection', 'communication', 'relationship', 'family', 'friends', 'love', 'care',
    'understanding', 'acceptance', 'supportive', 'compassion', 'empathy', 'sympathy', 'listening', 'validation', 'boundaries',
    'assertiveness', 'comfort', 'security', 'safety', 'trust', 'belonging', 'community', 'social', 'loneliness', 'isolation',
    'friendship', 'companionship', 'affection', 'mental illness', 'stigma', 'taboo', 'awareness', 'education', 'advocacy',
    'acceptance', 'understanding', 'treatment', 'recovery', 'progress', 'relapse', 'crisis', 'suicide', 'helpline',
    'support group', 'hotline', 'emergency', 'intervention', 'coping mechanism', 'stress management', 'anger management',
    'communication skills', 'conflict resolution', 'forgiveness', 'grief', 'loss', 'bereavement', 'trauma', 'PTSD',
    'self-harm', 'addiction', 'substance abuse', 'alcoholism', 'rehabilitation', 'medication', 'therapy', 'psychiatrist',
    'psychologist', 'counselor', 'therapist', 'mental health professional', 'diagnosis', 'treatment plan', 'medication management',
    'self-help', 'self-improvement', 'self-discovery', 'reflection', 'journaling', 'creative expression', 'art therapy',
    'music therapy', 'nature therapy', 'exercise', 'nutrition', 'sleep', 'rest', 'recharge', 'break', 'self-compassion',
    'self-love', 'self-acceptance', 'self-awareness', 'self-reflection', 'growth', 'journey', 'change', 'transformation',
    'diagnosis', 'assessment', 'evaluation', 'treatment', 'therapy', 'counseling', 'psychiatry', 'psychology',
    'psychotherapy', 'cognitive-behavioral therapy', 'CBT', 'dialectical behavior therapy', 'DBT', 'mindfulness-based therapy',
    'acceptance and commitment therapy', 'ACT', 'solution-focused therapy', 'family therapy', 'group therapy', 'individual therapy',
    'intervention', 'crisis intervention', 'mental status exam', 'symptomatology', 'psychopathology', 'co-occurring disorders',
    'dual diagnosis', 'substance use disorder', 'substance abuse treatment', 'addiction counseling', 'medication management',
    'psychopharmacology', 'antidepressants', 'anxiolytics', 'mood stabilizers', 'antipsychotics', 'psychoeducation',
    'relapse prevention', 'behavior modification', 'coping skills', 'stress management techniques', 'anger management techniques',
    'communication skills training', 'assertiveness training', 'conflict resolution skills', 'problem-solving skills',
    'emotion regulation', 'boundary setting', 'interpersonal skills', 'relationship building', 'therapeutic alliance',
    'transference', 'countertransference', 'empathy', 'validation', 'active listening', 'reflection', 'self-disclosure',
    'psychological assessment', 'personality assessment', 'intelligence testing', 'neuropsychological assessment',
    'diagnostic and statistical manual', 'DSM', 'International Classification of Diseases', 'ICD', 'case formulation',
    'treatment planning', 'collaborative goal-setting', 'progress monitoring', 'outcome evaluation', 'evidence-based practice',
    'clinical supervision', 'consultation', 'multidisciplinary team', 'referral', 'ethics', 'confidentiality', 'informed consent',
    'boundary ethics', 'duty to warn', 'mandatory reporting', 'scope of practice', 'professional competence', 'continuing education',
    'cultural competence', 'social determinants of health', 'intersectionality', 'trauma-informed care', 'resilience',
    'post-traumatic growth', 'grief counseling', 'loss and bereavement', 'childhood trauma', 'attachment theory',
    'developmental psychology', 'parent-child relationship', 'family dynamics', 'couple therapy', 'marital therapy',
    'divorce counseling', 'child and adolescent psychology', 'play therapy', 'art therapy', 'expressive therapies',
    'recreation therapy', 'occupational therapy', 'somatic experiencing', 'sensorimotor psychotherapy', 'eye movement desensitization and reprocessing',
    'EMDR', 'narrative therapy', 'solution-focused brief therapy', 'motivational interviewing', 'strengths-based approach',
    'client-centered therapy', 'Rogerian therapy', 'existential therapy', 'gestalt therapy', 'psychoanalysis', 'transpersonal psychology',
    'mind-body connection', 'holistic health', 'integrative medicine', 'complementary and alternative medicine', 'CAM',
    'biofeedback', 'neurofeedback', 'hypnotherapy', 'acupuncture', 'herbal medicine', 'nutritional counseling',
    'spirituality', 'well-being', 'holistic', 'inner peace', 'balance', 'harmony', 'meditation', 'mindfulness',
    'contemplation', 'transcendence', 'enlightenment', 'awakening', 'consciousness', 'serenity', 'wholeness', 'unity',
    'self-realization', 'presence', 'gratitude', 'compassion', 'forgiveness', 'joy', 'love', 'faith', 'hope', 'trust',
    'acceptance', 'surrender', 'connection', 'interconnectedness', 'oneness', 'divinity', 'sacred', 'divine', 'healing',
    'inner strength', 'resilience', 'peace of mind', 'soul', 'essence', 'purpose', 'meaning', 'transformation', 'growth',
    'journey', 'self-discovery', 'reflection', 'awareness', 'awakening', 'illumination', 'empowerment', 'inspiration',
    'inner guidance', 'intuition', 'wisdom', 'clarity', 'insight', 'holistic health', 'vitality', 'energy', 'life force',
    'chi', 'prana', 'breath', 'chakra', 'kundalini', 'yoga', 'mind-body connection', 'holistic healing', 'holistic nutrition',
    'energy healing', 'reiki', 'chiropractic', 'acupuncture', 'traditional Chinese medicine', 'Ayurveda', 'herbalism',
    'aromatherapy', 'crystal healing', 'sound healing', 'nature therapy', 'ecotherapy', 'forest bathing', 'shinrin-yoku',
    'sacred space', 'ritual', 'ceremony', 'prayer', 'chanting', 'mantra', 'affirmation', 'visualization', 'intention',
    'blessing', 'sacred geometry', 'mandala', 'altar', 'sacred text', 'scripture', 'prophet', 'saint', 'sage', 'guru',
    'shaman', 'medicine man', 'mystic', 'ascetic', 'monk', 'nun', 'yogi', 'spiritual teacher', 'spiritual practice',
    'spiritual journey', 'spiritual awakening', 'spiritual growth', 'spiritual transformation', 'spiritual guidance',
    'spiritual community', 'spiritual retreat', 'spiritual discipline', 'spiritual path', 'spiritual enlightenment',
    'spiritual wisdom', 'spiritual connection', 'spiritual healing', 'spiritual fulfillment', 'sacred relationship',
    'soulmate', 'twin flame', 'karma', 'dharma', 'samsara', 'nirvana', 'moksha', 'enlightened beings', 'saints and sages',
    'mystical experiences', 'divine love', 'universal consciousness', 'eternal truth', 'cosmic energy', 'divine purpose',
    'cosmic order', 'divine plan', 'universal laws', 'law of attraction', 'law of abundance', 'law of karma', 'law of dharma',
    'law of cause and effect', 'law of resonance', 'law of manifestation', 'law of unity', 'law of divine love', 'law of oneness',
    'law of grace', 'law of forgiveness', 'law of surrender', 'law of detachment', 'law of non-resistance', 'law of acceptance','life','sad','happy'
    ]
    return any(keyword in question.lower() for keyword in medical_keywords)
